# Project information
site_name: Maker Improvement Proposals
site_description: Governing better money
site_author: Andy Tudhope

# Specific to set up
site_url: https://andytudhope.github.io/mips/

# Repository
repo_name: makerdao/mips
repo_url: https://github.com/makerdao/mips
edit_uri: ""

extra_css: [extra.css]

# Configuration
theme:
  name: null
  custom_dir: material

  # 404 page
  static_templates:
    - 404.html

  # Don't include MkDocs' JavaScript
  include_search_page: false
  search_index_only: true

  # Default values, taken from mkdocs_theme.yml
  language: en
  features:
    - tabs
    #- instant
  palette:
    primary: black
    accent: lime
  font:
    text: Roboto
    code: Roboto Mono
  icon:
    logo: logo
  favicon: assets/favicon.png

# Plugins
plugins:
  - search
  - minify:
      minify_html: true

# Customization
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/makerdao
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/MakerDAO

# Extensions
markdown_extensions:
  - markdown.extensions.admonition
  - markdown.extensions.attr_list
  - markdown.extensions.codehilite:
      guess_lang: false
  - markdown.extensions.def_list
  - markdown.extensions.footnotes
  - markdown.extensions.meta
  - markdown.extensions.toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:pymdownx.emoji.twemoji
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  # - pymdownx.highlight:
  #     linenums_style: pymdownx-inline
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: andytudhope
      repo: mips
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - pymdownx.extra
  

# Page tree
nav:
  - Home: index.md
  - Accepted:
    - Active MIPs: 
      - 'Overview': 'accepted/index.md'
      - 'MIP 0': 'MIP0/mip0.md'
      - 'MIP 1': 'MIP1/mip1.md'
      - 'MIP 2': 'MIP2/mip2.md'
      - 'MIP 3': 'MIP3/mip3.md'
      - 'MIP 4': 'MIP4/mip4.md'
      - 'MIP 5': 'MIP5/mip5.md'
      - 'MIP 6': 'MIP6/mip6.md'
      - 'MIP 7': 'MIP7/mip7.md'
      - 'MIP 8': 'MIP8/mip8.md'
      - 'MIP 9': 'MIP9/mip9.md'
      - 'MIP 10': 'MIP10/mip10.md'
      - 'MIP 11': 'MIP11/mip11.md'
      - 'MIP 12': 'MIP12/mip12.md'
    - Active Sub-proposals:
      - 'Overview': 'accepted/subproposals/index.md'
      - MIP0:
        - 'Core Personnel Onboarding': 'MIP0/MIP0c12-Subproposals/MIP0c12-SP1.md'
      - MIP7:
        - 'Onboard Domain Team': 'MIP7/MIP7c3-Subproposals/MIP7c3-SP1.md'
      - MIP10:
        - 'List of Active Oracles': 'MIP10/MIP10c5-List-of-Active-Oracles.md'
        - 'List of Oracle Data Models': 'MIP10/MIP10c8-List-of-Oracle-Data-Models.md'
        - 'List of Oracle Whitelists': 'MIP10/MIP10c11-List-of-Oracle-Whitelists.md'
        - 'List of Feeds': 'MIP10/MIP10c17-List-of-Feeds.md'
    - Active Collateral:
      - 'Overview': 'accepted/collateral/index.md'
  - Process:
    - 'Overview': 'process/index.md'
    - 'Lifecycle': 'process/lifecycle.md'
  - Submit:
    - 'Introduction': 'submit/index.md'
    - MIP Templates:
      - 'General': 'MIP0/General-MIP-Template.md'
      - 'Technical': 'MIP0/Technical-MIP-Template.md'
    - Subproposal Templates:
      - MIP0:
        - 'Core Personnel Onboarding': 'MIP0/MIP0c12-Subproposal-Template.md'
        - 'Core Personal Offboarding': 'MIP0/MIP0c13-Subproposal-Template.md'
      - MIP1:
        - 'Problem Space': 'MIP1/MIP1c4-Subproposal-Template.md'
      - MIP3:
        - 'Default Inclusion Threshold': 'MIP3/MIP3c2-Subproposal-Template.md'
      - MIP4:
        - 'MIP Amendment': 'MIP4/MIP4c2-Subproposal-Template.md'
        - 'MIP Removal': 'MIP4/MIP4c3-Subproposal-Template.md'
      - MIP6:
        - 'Collateral Application Form': 'MIP6/MIP6c2-Collateral-Application-Template.md'
        - 'Change Collateral Application Form': 'MIP6/MIP6c3-Subproposal-Template.md'
      - MIP7:
        - 'Onboard Domain Team': 'MIP7/MIP7c3-Subproposal-Template.md'
        - 'Offboard Domain Team': 'MIP7/MIP7c4-Subproposal-Template.md'
      - MIP10:
        - 'Oracle Onboarding Request': 'MIP10/MIP10c2-Subproposal-Template.md'
        - 'Onboard Oracle': 'MIP10/MIP10c3-Subproposal-Template.md'
        - 'Oracle Offboarding': 'MIP10/MIP10c4-Subproposal-Template.md'
        - 'Update Oracle Data Model Request': 'MIP10/MIP10c6-Subproposal-Template.md'
        - 'Update Oracle Data Model': 'MIP10/MIP10c7-Subproposal-Template.md'
        - 'Whitelist Oracle Access': 'MIP10/MIP10c9-Subproposal-Template.md'
        - 'Whitelist Oracle Access': 'MIP10/MIP10c10-Subproposal-Template.md'
        - 'Update Oracle Access Fee': 'MIP10/MIP10c12-Subproposal-Template.md'
        - 'Appoint Dark Feed': 'MIP10/MIP10c13-Subproposal-Template.md'
        - 'Appoint Light Feed': 'MIP10/MIP10c14-Subproposal-Template.md'
        - 'Appoint Feed (OT)': 'MIP10/MIP10c15-Subproposal-Template.md'
        - 'Remove Feed': 'MIP10/MIP10c16-Subproposal-Template.md'
        - 'Update Feed Stipend': 'MIP10/MIP10c18-Subproposal-Template.md'
      - MIP11:
        - 'Onboarding General Risk Models': 'MIP11/MIP11c3-Subproposal-Template.md'
        - 'Offboarding General Risk Models': 'MIP11/MIP11c4-Subproposal-Template.md'
      - MIP12:
        - 'New Risk Parameters, Oracles, and Collateral Adapters': 'MIP12/MIP12c2-Subproposal-Template.md' 
  - Review:
    - 'Overview': 'review/index.md'
    - Current:
      - 'Overview': 'review/current/index.md'
    - Rejected:
      - 'Overview': 'review/rejected/index.md' 
  - Collateral Onboarding:
    - 'Guide': 'review/collateral/index.md'
    - 'Template': 'MIP6/MIP6c2-Collateral-Application-Template.md'
